-- 订阅表
CREATE TABLE IF NOT EXISTS subscriptions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url        TEXT      NOT NULL,
    content    TEXT      NOT NULL,
    type       TEXT      NOT NULL,
    status     INTEGER   NOT NULL DEFAULT -1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 创建唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_subscriptions_url ON subscriptions (url);

-- 代理服务器表
CREATE TABLE IF NOT EXISTS proxies
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT,
    name             TEXT      NOT NULL,
    domain           TEXT      NOT NULL,
    port             INTEGER   NOT NULL CHECK (port >= 0 AND port <= 65535),
    password        VARCHAR(255),
    type             TEXT      NOT NULL,
    config           TEXT      NOT NULL,
    ping             INTEGER            DEFAULT 0,
    download_speed   INTEGER            DEFAULT 0,
    upload_speed     INTEGER            DEFAULT 0,
    status           INTEGER   NOT NULL DEFAULT -1,
    pinned           BOOLEAN   NOT NULL DEFAULT FALSE,
    latest_test_time TIMESTAMP,
    created_at       TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP NOT NULL DEFAULT NOW(),

    -- 外键约束
    CONSTRAINT fk_proxies_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE SET NULL
);

-- 创建组合唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_domain_port_password ON proxies (domain, port, password);

-- 核心索引（基于前端查询模式的最小化索引）
CREATE INDEX IF NOT EXISTS idx_proxies_status ON proxies (status);
CREATE INDEX IF NOT EXISTS idx_proxies_type ON proxies (type);

-- 关键复合索引（覆盖90%前端查询场景）
CREATE INDEX IF NOT EXISTS idx_status_download ON proxies (status, download_speed DESC);
CREATE INDEX IF NOT EXISTS idx_status_ping ON proxies (status, ping DESC);

-- 测速历史记录表
CREATE TABLE IF NOT EXISTS speed_test_histories
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proxy_id BIGINT NOT NULL,
    ping           INTEGER   NOT NULL DEFAULT 0,
    download_speed INTEGER   NOT NULL DEFAULT 0,
    upload_speed   INTEGER   NOT NULL DEFAULT 0,
    test_time      TIMESTAMP NOT NULL DEFAULT NOW(),
    created_at     TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_proxy_id ON speed_test_histories (proxy_id);
CREATE INDEX idx_speed_test_histories_proxy_created ON speed_test_histories (proxy_id, created_at DESC);

-- 流量统计表
CREATE TABLE IF NOT EXISTS traffic_statistics
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proxy_id       BIGINT    NOT NULL,
    download_total BIGINT    NOT NULL DEFAULT 0,
    upload_total   BIGINT    NOT NULL DEFAULT 0,
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 创建唯一索引，确保每个代理只有一条流量统计记录
CREATE UNIQUE INDEX IF NOT EXISTS idx_traffic_proxy_id ON traffic_statistics (proxy_id);

-- IP质量检测相关表

-- IP地址表
CREATE TABLE IF NOT EXISTS ip_addresses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip         VARCHAR(45) NOT NULL UNIQUE,
    ip_type INTEGER NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- 创建索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_ip_addresses_ip ON ip_addresses (ip);

-- 代理IP关联表
CREATE TABLE IF NOT EXISTS proxy_ip_addresses
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proxy_id        BIGINT    NOT NULL,
    ip_addresses_id BIGINT    NOT NULL,
    ip_type INTEGER NOT NULL,
    latest  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 创建索引和唯一约束
CREATE UNIQUE INDEX IF NOT EXISTS uidx_proxy_ip_addresses_proxy_id_ip_addresses_id_ip_type ON proxy_ip_addresses (proxy_id, ip_addresses_id, ip_type);
CREATE INDEX IF NOT EXISTS idx_proxy_ip_addresses_ip_addresses_id ON proxy_ip_addresses (ip_addresses_id);
CREATE INDEX IF NOT EXISTS idx_proxy_ip_addresses_proxy_id ON proxy_ip_addresses (proxy_id);

-- IP信息表,每个ip+检测器一条记录
CREATE TABLE IF NOT EXISTS ip_infos
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_addresses_id BIGINT       NOT NULL,
    detector        VARCHAR(255) NOT NULL,
    risk JSONB,
    geo  JSONB,
    raw             TEXT,
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_ip_infos_ip_addresses_id ON ip_infos (ip_addresses_id);
CREATE INDEX IF NOT EXISTS idx_ip_infos_detector ON ip_infos (detector);

-- ip base info，从上面的表算出来的
CREATE TABLE IF NOT EXISTS ip_base_infos
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_addresses_id BIGINT    NOT NULL,
    risk_level      VARCHAR(10),
    country_code    VARCHAR(5),
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ip_base_infos_ip_addresses_id ON ip_base_infos (ip_addresses_id);

-- unlock info
CREATE TABLE IF NOT EXISTS ip_unlock_infos
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_addresses_id BIGINT    NOT NULL,
    app_name        VARCHAR(50),
    status          VARCHAR(10),
    region          VARCHAR(10),
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ip_unlock_infos_ip_addresses_id ON ip_unlock_infos (ip_addresses_id);

-- 系统配置表
CREATE TABLE IF NOT EXISTS system_configs
(
    key        VARCHAR(255) PRIMARY KEY,
    value      TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 订阅自定义配置表
CREATE TABLE IF NOT EXISTS subscription_configs
(
    subscription_id BIGINT PRIMARY KEY,
    auto_update     BOOLEAN   NOT NULL DEFAULT TRUE,
    update_interval TEXT      NOT NULL,
    use_proxy       BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);