-- 订阅表
CREATE TABLE IF NOT EXISTS subscriptions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url        TEXT      NOT NULL,
    content    TEXT      NOT NULL,
    type       TEXT      NOT NULL,
    status     INTEGER   NOT NULL DEFAULT -1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 创建唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_subscriptions_url ON subscriptions (url);

-- 代理服务器表
CREATE TABLE IF NOT EXISTS proxies
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT,
    name             TEXT      NOT NULL,
    domain           TEXT      NOT NULL,
    port             INTEGER   NOT NULL CHECK (port >= 0 AND port <= 65535),
    type             TEXT      NOT NULL,
    config           TEXT      NOT NULL,
    ping             INTEGER            DEFAULT 0,
    download_speed   INTEGER            DEFAULT 0,
    upload_speed     INTEGER            DEFAULT 0,
    status           INTEGER   NOT NULL DEFAULT -1,
    pinned           BOOLEAN   NOT NULL DEFAULT FALSE,
    latest_test_time TIMESTAMP,
    created_at       TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP NOT NULL DEFAULT NOW(),

    -- 外键约束
    CONSTRAINT fk_proxies_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE SET NULL
);

-- 创建组合唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_domain_port ON proxies (domain, port);

-- 核心索引（基于前端查询模式的最小化索引）
CREATE INDEX IF NOT EXISTS idx_proxies_status ON proxies (status);
CREATE INDEX IF NOT EXISTS idx_proxies_type ON proxies (type);

-- 关键复合索引（覆盖90%前端查询场景）
CREATE INDEX IF NOT EXISTS idx_status_download ON proxies (status, download_speed DESC);
CREATE INDEX IF NOT EXISTS idx_status_ping ON proxies (status, ping DESC);

-- 测速历史记录表
CREATE TABLE IF NOT EXISTS speed_test_histories
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proxy_id BIGINT NOT NULL,
    ping           INTEGER   NOT NULL DEFAULT 0,
    download_speed INTEGER   NOT NULL DEFAULT 0,
    upload_speed   INTEGER   NOT NULL DEFAULT 0,
    test_time      TIMESTAMP NOT NULL DEFAULT NOW(),
    created_at     TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_proxy_id ON speed_test_histories (proxy_id);

-- 流量统计表
CREATE TABLE IF NOT EXISTS traffic_statistics
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proxy_id       BIGINT    NOT NULL,
    download_total BIGINT    NOT NULL DEFAULT 0,
    upload_total   BIGINT    NOT NULL DEFAULT 0,
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 创建唯一索引，确保每个代理只有一条流量统计记录
CREATE UNIQUE INDEX IF NOT EXISTS idx_traffic_proxy_id ON traffic_statistics (proxy_id);