version: '3'

services:
  passwall:
    image: passwall:latest
    container_name: passwall
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
    environment:
      - CONFIG_PATH=/app/config.yaml
