version: '3'

services:
  passwall:
    image: pakro888/passwall:latest
    container_name: passwall
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
    environment:
      - PASSWALL_TOKEN=your_token_here
      - CONFIG_PATH=/app/config.yaml
      - TZ=Asia/Shanghai
    #      you can get free user and api key from https://scamalytics.com/ip/api/pricing
    #      - SCAMALYTICS_USER=your_scamalytics_user_here
    #      - SCAMALYTICS_API_KEY=your_scamalytics_api_key_here
    depends_on:
      - postgres


  postgres:
    image: postgres:17-alpine
    container_name: passwall-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=passwall
      - POSTGRES_PASSWORD=passwall
      - POSTGRES_DB=passwall
      - TZ=Asia/Shanghai
