token: "123456"   # 获取订阅链接时，token必填
concurrent: 30

server:
  address: "127.0.0.1:8080"

database:
  driver: "sqlite"
  dsn: "passwall.db"

proxy:
  enabled: false  # 是否启用代理
  url: "socks5://127.0.0.1:7890"  # 代理地址，支持http和socks5

cron_jobs:
  - name: "每6小时测试所有节点"
    schedule: "0 * */6 * * *"
    reload_subscribe_config: true
    test_all: true
    test_new: false
    test_failed: false
    test_speed: false
    concurrent: 30

  - name: "每天凌晨3点测试节点速度"
    schedule: "0 0 3 * * *"
    reload_subscribe_config: false
    test_all: false
    test_new: false
    test_failed: false
    test_speed: true
    concurrent: 1 