name: Docker Build

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
      - 'test*'
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tags
        id: docker_tags
        run: |
          if [[ $GITHUB_REF == refs/tags/test ]]; then
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/passwall:test" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/passwall:$VERSION,${{ secrets.DOCKERHUB_USERNAME }}/passwall:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/passwall:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-arm64:
    runs-on: ubuntu-latest-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tags
        id: docker_tags
        run: |
          if [[ $GITHUB_REF == refs/tags/test ]]; then
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/passwall:test" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/passwall:$VERSION,${{ secrets.DOCKERHUB_USERNAME }}/passwall:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/passwall:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max