name: Docker Build

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
      - 'test*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tags
        id: docker_tags
        run: |
          if [[ $GITHUB_REF == refs/tags/test ]]; then
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/passwall:test" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/passwall:$VERSION,${{ secrets.DOCKERHUB_USERNAME }}/passwall:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/passwall:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        run: |
          IFS=',' read -ra TAGS <<< "${{ steps.docker_tags.outputs.tags }}"
          for tag in "${TAGS[@]}"; do
            echo "Building and pushing: $tag"
            docker build --no-cache -t $tag .
            docker push $tag
          done